def label = "pod-angular-${UUID.randomUUID().toString()}"

podTemplate(label: label, cloud: 'openshift', containers: [    
    containerTemplate(image: 'docker.io/petenorth/nodejs8-openshift-slave', ttyEnabled: false, name: 'jnlp',args: '${computer.jnlpmac} ${computer.name}')
  ]) {

  node(label) {   
      
      container('jnlp') {

        stages{
          stage ('checkout'){
            steps{              
               git 'https://github.com/marcelolucio1982/angular-5-example.git'
                sh 'node -v'
            }
          }
          stage ('install modules'){
            steps{
              sh 'npm install'
            }
          }
          stage ('test'){
            steps{
              sh "$(npm bin)/ng test --single-run --browsers Chrome_no_sandbox"
            }
            post {
                always {
                  junit "test-results.xml"
                }
            }
          }
          stage ('code quality'){
            steps{
              sh "$(npm bin)/ng lint"
            }
          }
          stage ('build') {
            steps{
              sh "$(npm bin)/ng build --prod --build-optimizer"
            }
          }
          stage ('build image') {
            steps{
              sh "rm -rf node_modules"
              sh "oc start-build angular-5-example --from-dir=. --follow"
            }
          }
        }
          
      }
    
  }
}


  
